<script setup lang="ts">
import type { ExtendedColDef } from '@/components/modules/grid-table'
import { GridTable } from '@/components/modules/grid-table'

const columnDefs: ExtendedColDef[] = [
  {
    field: 'id',
    headerName: 'ID',
    pinned: 'left',
  },
  {
    field: 'name',
    headerName: '姓名',
  },
  {
    field: 'age',
    headerName: '年龄',
  },
  {
    field: 'email',
    headerName: '邮箱',
  },
  {
    field: 'department',
    headerName: '部门',
  },
  {
    field: 'position',
    headerName: '职位',
  },
  {
    field: 'salary',
    headerName: '薪资',
    sortable: true,
    valueFormatter: (params: any) => {
      return `¥${params.value?.toLocaleString() || 0}`
    },
  },
  {
    field: 'status',
    headerName: '状态',
    valueGetter: (params: any) => {
      const status = params.data?.status
      const statusMap = {
        active: '在职',
        inactive: '离职',
        pending: '待定',
      }
      return statusMap[status as keyof typeof statusMap] || status
    },
  },
  {
    field: 'joinDate',
    headerName: '入职日期',
    valueFormatter: (params: any) => {
      if (!params.value) {
        return ''
      }
      return new Date(params.value).toLocaleDateString('zh-CN')
    },
  },
  {
    field: 'phone',
    headerName: '电话',
  },
  {
    field: 'address',
    headerName: '地址',
  },
]

const rowData = [
  {
    id: 1,
    name: '张三',
    age: 28,
    email: 'zhangsan@example.com',
    department: '技术部',
    position: '前端工程师',
    salary: 15000,
    status: 'active',
    joinDate: '2022-03-15',
    phone: '13800138001',
    address: '北京市朝阳区',
  },
  {
    id: 2,
    name: '李四',
    age: 32,
    email: 'lisi@example.com',
    department: '技术部',
    position: '后端工程师',
    salary: 18000,
    status: 'active',
    joinDate: '2021-08-20',
    phone: '13800138002',
    address: '上海市浦东新区',
  },
  {
    id: 3,
    name: '王五',
    age: 25,
    email: 'wangwu@example.com',
    department: '设计部',
    position: 'UI设计师',
    salary: 12000,
    status: 'active',
    joinDate: '2023-01-10',
    phone: '13800138003',
    address: '广州市天河区',
  },
  {
    id: 4,
    name: '赵六',
    age: 35,
    email: 'zhaoliu@example.com',
    department: '产品部',
    position: '产品经理',
    salary: 20000,
    status: 'active',
    joinDate: '2020-06-01',
    phone: '13800138004',
    address: '深圳市南山区',
  },
  {
    id: 5,
    name: '钱七',
    age: 29,
    email: 'qianqi@example.com',
    department: '运营部',
    position: '运营专员',
    salary: 10000,
    status: 'inactive',
    joinDate: '2022-11-15',
    phone: '13800138005',
    address: '杭州市西湖区',
  },
  {
    id: 6,
    name: '孙八',
    age: 27,
    email: 'sunba@example.com',
    department: '技术部',
    position: '测试工程师',
    salary: 13000,
    status: 'active',
    joinDate: '2023-05-20',
    phone: '13800138006',
    address: '成都市武侯区',
  },
  {
    id: 7,
    name: '周九',
    age: 31,
    email: 'zhoujiu@example.com',
    department: '市场部',
    position: '市场专员',
    salary: 11000,
    status: 'active',
    joinDate: '2022-09-01',
    phone: '13800138007',
    address: '武汉市江汉区',
  },
  {
    id: 8,
    name: '吴十',
    age: 26,
    email: 'wushi@example.com',
    department: '人事部',
    position: '人事专员',
    salary: 9000,
    status: 'pending',
    joinDate: '2023-08-15',
    phone: '13800138008',
    address: '南京市鼓楼区',
  },
  {
    id: 9,
    name: '郑十一',
    age: 33,
    email: 'zhengshiyi@example.com',
    department: '财务部',
    position: '会计',
    salary: 14000,
    status: 'active',
    joinDate: '2021-12-01',
    phone: '13800138009',
    address: '西安市雁塔区',
  },
  {
    id: 10,
    name: '王十二',
    age: 24,
    email: 'wangshier@example.com',
    department: '技术部',
    position: '实习生',
    salary: 5000,
    status: 'active',
    joinDate: '2023-10-01',
    phone: '13800138010',
    address: '重庆市渝中区',
  },
  {
    id: 11,
    name: '李十三',
    age: 30,
    email: 'lishisan@example.com',
    department: '销售部',
    position: '销售经理',
    salary: 16000,
    status: 'active',
    joinDate: '2022-01-15',
    phone: '13800138011',
    address: '天津市和平区',
  },
  {
    id: 12,
    name: '张十四',
    age: 28,
    email: 'zhangshisi@example.com',
    department: '客服部',
    position: '客服主管',
    salary: 12000,
    status: 'active',
    joinDate: '2022-07-01',
    phone: '13800138012',
    address: '苏州市姑苏区',
  },
  {
    id: 13,
    name: '刘十五',
    age: 35,
    email: 'liushiwu@example.com',
    department: '技术部',
    position: '架构师',
    salary: 25000,
    status: 'active',
    joinDate: '2020-03-01',
    phone: '13800138013',
    address: '长沙市岳麓区',
  },
  {
    id: 14,
    name: '陈十六',
    age: 27,
    email: 'chenshiliu@example.com',
    department: '设计部',
    position: '平面设计师',
    salary: 11000,
    status: 'active',
    joinDate: '2023-02-20',
    phone: '13800138014',
    address: '福州市鼓楼区',
  },
  {
    id: 15,
    name: '杨十七',
    age: 29,
    email: 'yangshiqi@example.com',
    department: '运营部',
    position: '运营经理',
    salary: 15000,
    status: 'active',
    joinDate: '2022-05-10',
    phone: '13800138015',
    address: '郑州市金水区',
  },
]
</script>

<template lang="pug">
.full
  GridTable(:column-defs='columnDefs', :row-data='rowData', :enable-zebra-stripe='true')
</template>
