name: 版权保护检查

on:
  push:
    branches: [main, develop, feature]
  pull_request:
    branches: [main, develop]

jobs:
  copyright-check:
    runs-on: ubuntu-latest
    name: 检查版权保护

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 运行版权检查
        run: pnpm copyright:check

      - name: 验证许可证文件
        run: |
          if [ ! -f "LICENSE" ]; then
            echo "❌ 缺少 LICENSE 文件"
            exit 1
          fi

          if ! grep -q "版权所有 (c) 2025 chichuang" LICENSE; then
            echo "❌ LICENSE 文件缺少版权声明"
            exit 1
          fi

          echo "✅ LICENSE 文件检查通过"

      - name: 检查关键文件版权
        run: |
          files=(
            "src/main.ts"
            "src/App.vue"
            "vite.config.ts"
            "package.json"
            "scripts/copyright-protection.ts"
          )

          for file in "${files[@]}"; do
            if [ -f "$file" ]; then
              if grep -q "Copyright (c) 2025 chichuang" "$file"; then
                echo "✅ $file 包含版权声明"
              else
                echo "❌ $file 缺少版权声明"
                exit 1
              fi
            else
              echo "⚠️  $file 文件不存在"
            fi
          done

      - name: 检查自定义许可证
        run: |
          if ! grep -q "商业用途" LICENSE; then
            echo "❌ LICENSE 文件缺少商业限制条款"
            exit 1
          fi

          if ! grep -q "商业授权" LICENSE; then
            echo "❌ LICENSE 文件缺少商业授权条款"
            exit 1
          fi

          echo "✅ 自定义许可证检查通过"
